config/routes.rb
Rails.application.routes.draw do
  root 'contributions#index'

  resources :contributions do
    member do
      post '/vote', to: "contributions#vote_up"
      delete '/vote', to: "contributions#unvote"

      resources :comments
    end
  end

  resources :comments do
    member do
      post '/vote', to: "comments#vote_up"
      delete '/vote', to: "comments#unvote"

      resources :comments
    end
  end

  resources :users do
    member do
      get '/contributions', to: "users#contributions"
      get '/voted_contributions', to: "users#voted_contributions"
      get '/comments', to: "users#comments"
      get '/voted_comments', to: "users#voted_comments"
    end
  end

  get '/submit', to: "contributions#new"
  get '/newest', to: "contributions#newest"
  get '/ask', to: "contributions#ask"

  # Authentication
  post '/login', to:'sessions#authenticate'

  namespace :api do
    resources :users, only: %i(index update show) do
      member do
        get '/contributions', to: "users#contributions"
        get '/voted_contributions', to: "users#voted_contributions"
        get '/comments', to: "users#comments"
        get '/voted_comments', to: "users#voted_comments"
      end
    end

    resources :contributions do
      member do
        post '/vote', to: "contributions#vote_up"
        delete '/vote', to: "contributions#unvote"
        post '/comments', to: "comments#createFromContribution"
      end
    end

    resources :comments, only: %i(show update) do
      member do
        post '/vote', to: "comments#vote_up"
        delete '/vote', to: "comments#unvote"
        post '/replies', to: "comments#createFromComment"
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :text, presence: true
end

app/controllers/api/comments_controller.rb
module Api
  class CommentsController < ApplicationController
    def index
      if params[:type] == 'contribution'
        contribution = Contribution.find(params[:id])
        @comments = contribution.comments
      else
        comment = Comment.find(params[:id])
        @comments = comment.comments
      end

      respond_to do |format|
        format.json { render :index, status: :ok, resource: @comments }
      end
    end

    def vote_up
      @comment = Comment.find(params[:id])
      user = User.find_by(apikey: request.headers[:apikey])
      @comment.upvote_from user
      head :ok
    end

    def unvote
      @comment = Comment.find(params[:id])
      user = User.find_by(apikey: request.headers[:apikey])
      @comment.unvote_up user if user.voted_for?(@comment)
      head :ok
    end

    def show
      @comment = Comment.find(params[:id])

      respond_to do |format|
        if @comment
          format.json { render :show, status: :ok, resource: @comment }
        else
          format.json { render json: @comment.errors, status: 404 }
        end
      end
    end

    def create
      if params[:type] == 'contribution'
        contribution = Contribution.find(params[:id])
        @comment = contribution.comments.new(comment_params)
      else
        comment = Comment.find(params[:id])
        @comment = comment.comments.new(comment_params)
      end

      respond_to do |format|
        if @comment.save
          format.json { render :show, status: :created, resource: @comment }
        else
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    def createFromContribution
       contribution = Contribution.find(params[:id])
       @user = User.find_by(apikey: request.headers[:apikey])
       @comment = contribution.comments.new(comment_params.merge!({user_id: @user.id}))

      respond_to do |format|
        if @comment.save
          format.json { render :show, status: :created, resource: @comment }
        else
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    def createFromComment
      comment = Comment.find(params[:id])
      @user = User.find_by(apikey: request.headers[:apikey])
      @comment = comment.comments.new(comment_params.merge!({user_id: @user.id}))

      respond_to do |format|
        if @comment.save
          format.json { render :show, status: :created, resource: @comment }
        else
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @comment = Comment.find(params[:id])

      if request.headers[:apikey] == @comment.user.apikey
        respond_to do |format|
          if @comment.update(comment_params)
            format.json { render :show, status: :accepted, resource: @comment }
          else
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
      end
    end


    def destroy
      @comment = Comment.find(params[:id])

      if request.headers[:apikey] == @comment.user.apikey
        respond_to do |format|
          if @comment.destroy
            format.json { head :ok }
          else
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
      end
    end

    private

    def comment_params
      params.permit(:text)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_user_id_param, only: [:create, :update]

  def vote_up
    @comment = Comment.find(params[:id])
    @comment.upvote_from current_user
    redirect_back fallback_location: :fallback_location
  end

  def unvote
    @comment = Comment.find(params[:id])
    @comment.unvote_up current_user
    redirect_back fallback_location: :fallback_location
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def create
    if current_user.present?
      @commentable = Contribution.find(params[:id]) if params[:type] == 'contribution'
      @commentable = Comment.find(params[:id]) if params[:type] == 'comment'
      @comment = @commentable.comments.new(comment_params.merge!({user_id: params[:comment][:user_id]}))
      respond_to do |format|
        if @comment.save
          format.html { redirect_back fallback_location: :fallback_location, notice: 'The comment was successfully created.' }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { redirect_back fallback_location: :fallback_location }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else 
       redirect_to '/auth/google_oauth2'
    end
  end

  def destroy
    if @comment.user.id = current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to contributions_url, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_comment
      return if @comment = Comment.find(params[:id])
    end

    def set_user_id_param
      params[:comment][:user_id] = current_user.id if current_user
    end

    def comment_params
      params.require(:comment).permit(:text, :type)
    end
end

app/views/comments/_comment.html.erb
<div class="media" id="comment-<%= comment.id %>">
  <% if comment.id != nil %>
    <div class="media-left media-top">
      <% if current_user.present? && comment.user_id == current_user.id %>
        <span class="vote glyphicon glyphicon-asterisk"></span>
      <% elsif current_user.present? && comment.user_id != current_user.id && current_user.voted_for?(comment) %>
        <%= link_to vote_comment_path(comment), method: :delete do %>
          <span class="vote glyphicon glyphicon-circle-arrow-down"></span>
        <% end %>
      <% elsif %>
        <%= link_to vote_comment_path(comment), method: :post do %>
          <span class="vote glyphicon glyphicon-circle-arrow-up"></span>
        <% end %>
      <% end %>
    </div>
    <div class="media-body">
      <div class="media-header">
      <%= link_to comment.user.name, comment.user%> <%= time_ago_in_words(comment.created_at)+" ago"%>
      </div>
      <div class="comment-text"><%= comment.text %></div>
      <div class="comment-reply">
        <%= link_to "Reply", "/comments/#{comment.id}" %>
      </div>
      
      <% if comment.comments.any? %>
        <div class="comments">
          <%= render comment.comments %>
        </div>
      <% end %>
    </div>
    
  <% end %>
</div>

app/views/comments/show.html.erb
<% provide(:title, "#{@comment.user.name}") %>
<h2><%= @comment.text %></h2>

<div class="comment_info">
  <table class="table">
    <tr>
      <td><strong style="float:right;">Points:</strong></td>
      <td><%= @comment.get_upvotes.size %>
        <% if current_user.present? && @comment.user_id == current_user.id %>
          <span class="vote glyphicon glyphicon-asterisk"></span>
        <% elsif current_user.present? && @comment.user_id != current_user.id && current_user.voted_for?(@comment) %>
          <%= link_to vote_comment_path(@comment), method: :delete do %>
            <span class="vote glyphicon glyphicon-circle-arrow-down"></span>
          <% end %>
        <% elsif %>
          <%= link_to vote_comment_path(@comment), method: :post do %>
            <span class="vote glyphicon glyphicon-circle-arrow-up"></span>
          <% end %>
        <% end %>
      </td>
      <td><strong style="float:right;">By:</strong></td>
      <td><%= @comment.user.name %></td>
      <td><strong style="float:right;">Created:</strong></td>
      <td><%= time_ago_in_words(@comment.created_at)+" ago" %></td>
    </tr>
  </table>
  
  <div>
    <%= form_for(@comment.comments.new) do |f|%>
      <%= hidden_field_tag :type , 'comment' %>
      <div class="form-group">
      <%= f.text_area :text, class: "form-control" %>
    </div>
    <div>
      <%= f.submit "submit", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

<% if @comment.comments.any? %>
<div class="comments">
  <%= render @comment.comments %>
</div>
<% end %>