config/routes.rb
Rails.application.routes.draw do
  root 'contributions#index'

  resources :contributions do
    member do
      post '/vote', to: "contributions#vote_up"
      delete '/vote', to: "contributions#unvote"

      resources :comments
    end
  end

  resources :comments do
    member do
      post '/vote', to: "comments#vote_up"
      delete '/vote', to: "comments#unvote"

      resources :comments
    end
  end

  resources :users do
    member do
      get '/contributions', to: "users#contributions"
      get '/voted_contributions', to: "users#voted_contributions"
      get '/comments', to: "users#comments"
      get '/voted_comments', to: "users#voted_comments"
    end
  end

  get '/submit', to: "contributions#new"
  get '/newest', to: "contributions#newest"
  get '/ask', to: "contributions#ask"

  # Authentication
  post '/login', to:'sessions#authenticate'

  namespace :api do
    resources :users, only: %i(index update show) do
      member do
        get '/contributions', to: "users#contributions"
        get '/voted_contributions', to: "users#voted_contributions"
        get '/comments', to: "users#comments"
        get '/voted_comments', to: "users#voted_comments"
      end
    end

    resources :contributions do
      member do
        post '/vote', to: "contributions#vote_up"
        delete '/vote', to: "contributions#unvote"
        post '/comments', to: "comments#createFromContribution"
      end
    end

    resources :comments, only: %i(show update) do
      member do
        post '/vote', to: "comments#vote_up"
        delete '/vote', to: "comments#unvote"
        post '/replies', to: "comments#createFromComment"
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :contributions

  validates :name, :email, :apikey, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    unless user
      user = User.create(name: data['name'],
                         email: data['email'],
                         apikey: data['name'].split("").shuffle.join.gsub(' ', ''))
    end

    user
  end

  def self.create_user_for_google(data)
    where(email: data["email"]).first_or_initialize.tap do |user|
      user.name=data["name"]
      user.email=data["email"]
      user.apikey=data["at_hash"]
      user.save!
    end
  end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def index
      @users = User.all

      respond_to do |format|
        format.json { render :index, status: :ok, resource: @users }
      end
    end

    def show
      @user = User.find(params[:id])

      respond_to do |format|
        if @user
          format.json { render :show, status: :ok, resource: @user }
        else
          format.json { render json: @user.errors, status: 404 }
        end
      end
    end

    def update
      @user = User.find(params[:id])

      if request.headers[:apikey] == @user.apikey
        respond_to do |format|
          if @user.update(user_params)
            format.json { render :show, status: :ok, resource: @user }
          else
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end
    end

    def contributions
      @user = User.find(params[:id])
      @contributions = @user.contributions
      respond_to do |format|
        format.json { render 'api/contributions/index', status: :ok, resource: @contributions }
      end
    end

    def voted_contributions
      @user = User.find(params[:id])
      @contributions = @user.get_voted Contribution

      respond_to do |format|
        if request.headers[:apikey] == @user.apikey
          format.json { render 'api/contributions/index', status: :ok, resource: @contributions }
        else
          format.json { render json: { error: "Wrong api_key" }, status: :unprocessable_entity }
        end
      end
    end

    def comments
      @user = User.find(params[:id])
      @comments = Comment.where(user_id: @user.id)
      respond_to do |format|
        format.json { render 'api/comments/index', status: :ok, resource: @comments }
      end
    end

    def voted_comments
      @user = User.find(params[:id])
      @comments = @user.get_voted Comment

      respond_to do |format|
        if request.headers[:apikey] == @user.apikey
          format.json { render 'api/comments/index', status: :ok, resource: @comments }
        else
          format.json { render json: { error: "Wrong api_key" }, status: :unprocessable_entity }
        end
      end
    end

    private

    def user_params
      params.permit(:about)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show contributions voted_contributions voted_comments comments)

  def show
  end

  def new
    @user = User.new
  end

  def contributions
    @contributions = @user.contributions
  end

  def voted_contributions
    @contributions = @user.get_voted Contribution
  end

  def comments
    @comments = Comment.where(user_id: current_user.id)
  end

  def voted_comments
    @comments = current_user.get_voted Comment
  end

  def create
    @user = User.new(user_params.merge({ apikey: params[:name].split("").shuffle.join }))

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/comments.html.erb
<% provide(:title, "#{@user.name}'s comments") %>
<% if @comments.any? %>
  <div class="comments">
    <%= render @comments %>
  </div>
<% end %>

app/views/users/contributions.html.erb
<% provide(:title, "#{@user.name}'s contributions") %>
<% if @contributions.any? %>
  <ol class="contributions">
    <%= render @contributions %>
  </ol>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>
<div class="col-md-8">
  <table class="table">
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @user.name %></td>
    <tr>
    <tr>
      <td><strong>Email:</strong></td>
      <td><%= @user.email %></td>
    <tr>
    <tr>
      <td><strong>Created:</strong></td>
      <td><%= time_ago_in_words(@user.created_at) %></td>
    <tr>

    <% if current_user.id == @user.id %>
      <tr>
        <td><strong>Api key:</strong></td>
        <td><%= @user.apikey %></td>
      </tr>
    <% end %>

    <tr>
      <td></td>
      <td>
        <%= link_to "Contributions", contributions_user_path, class: "btn btn-primary" %>
        <%= link_to "Voted Contributions", voted_contributions_user_path, class: "btn btn-primary" %>
      </td>
    </tr>
    <% if !current_user.nil? && @user.id == current_user.id %>
      <tr>
        <td></td>
        <td>
          <%= link_to "Comments", comments_user_path, class: "btn btn-success" %>
          <%= link_to "Voted Comment", voted_comments_user_path, class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/voted_comments.html.erb
<% provide(:title, "#{@user.name}'s favorites comments") %>
<% if @comments.any? %>
  <div class="comments">
    <%= render @comments %>
  </div>
<% end %>

app/views/users/voted_contributions.html.erb
<% provide(:title, "#{@user.name}'s favorites contributions") %>
<% if @contributions.any? %>
  <ol class="contributions">
    <%= render @contributions %>
  </ol>
<% end %>