config/routes.rb
Rails.application.routes.draw do
  root 'contributions#index'

  resources :contributions do
    member do
      post '/vote', to: "contributions#vote_up"
      delete '/vote', to: "contributions#unvote"

      resources :comments
    end
  end

  resources :comments do
    member do
      post '/vote', to: "comments#vote_up"
      delete '/vote', to: "comments#unvote"

      resources :comments
    end
  end

  resources :users do
    member do
      get '/contributions', to: "users#contributions"
      get '/voted_contributions', to: "users#voted_contributions"
      get '/comments', to: "users#comments"
      get '/voted_comments', to: "users#voted_comments"
    end
  end

  get '/submit', to: "contributions#new"
  get '/newest', to: "contributions#newest"
  get '/ask', to: "contributions#ask"

  # Authentication
  post '/login', to:'sessions#authenticate'

  namespace :api do
    resources :users, only: %i(index update show) do
      member do
        get '/contributions', to: "users#contributions"
        get '/voted_contributions', to: "users#voted_contributions"
        get '/comments', to: "users#comments"
        get '/voted_comments', to: "users#voted_comments"
      end
    end

    resources :contributions do
      member do
        post '/vote', to: "contributions#vote_up"
        delete '/vote', to: "contributions#unvote"
        post '/comments', to: "comments#createFromContribution"
      end
    end

    resources :comments, only: %i(show update) do
      member do
        post '/vote', to: "comments#vote_up"
        delete '/vote', to: "comments#unvote"
        post '/replies', to: "comments#createFromComment"
      end
    end
  end
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  acts_as_votable

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  REGEX_URL = /\Ahttps?:\/\/([^\/]+)\/?/
  validate :text_url_presence
  validates :user, :title, presence: true
  validates :url, uniqueness: true, if: :url?
  validates :url, format: { with: REGEX_URL }, on: :create, if: :url?

  scope :urls, -> { where(ask: false) }
  scope :questions, -> { where(ask: true) }

  def get_from
    REGEX_URL.match(url) ? REGEX_URL.match(url)[1] : ""
  end

  private

  def text_url_presence
    unless text.present? && url.present?
      set_ask
      return
    end

    errors.add :base, "This contribution has url and text and can only have one."
  end

  def set_ask
    update_attribute(:ask, text.present?)
  end

  def url?
    ask == false;
  end
end

app/controllers/api/contributions_controller.rb
module Api
  class ContributionsController < ApplicationController
    def index
      @contributions = Contribution.all if params[:type].blank?
      @contributions = Contribution.questions if params[:type] == 'ask'
      @contributions = Contribution.urls if params[:type] == 'url'
      @contributions = Contribution.all.sort_by { |c| -c.get_upvotes.size } if params[:type] == 'votes'
      @contributions = Contribution.all.order created_at: :desc if params[:type] == 'new'

      respond_to do |format|
        format.json { render :index, status: :ok, resource: @contributions }
      end
    end

    def vote_up
      @contribution = Contribution.find(params[:id])
      user = User.find_by(apikey: request.headers[:apikey])
      @contribution.upvote_from user if not user.voted_for?(@contribution)
      head :ok
    end

    def unvote
      @contribution = Contribution.find(params[:id])
      user = User.find_by(apikey: request.headers[:apikey])
      @contribution.unvote_up user if user.voted_for?(@contribution)
      head :ok
    end

    def show
      @contribution = Contribution.find(params[:id])

      respond_to do |format|
        if @contribution
          format.json { render :show, status: :ok, resource: @contribution }
        else
          format.json { render json: @contribution.errors, status: 404 }
        end
      end
    end

    def create
      @userid = User.find_by(apikey: request.headers[:apikey])
      @contribution = Contribution.new(contribution_params.merge!({user_id: @userid.id}))

      respond_to do |format|
        if @contribution.save
          format.json { render :show, status: :created, resource: @contribution }
        else
          format.json { render json: @contribution.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @contribution = Contribution.find(params[:id])

      if request.headers[:apikey] == @contribution.user.apikey
        respond_to do |format|
          if @contribution.update(contribution_params)
            format.json { render :show, status: :created, resource: @contribution }
          else
            format.json { render json: @contribution.errors, status: :unprocessable_entity }
          end
        end
      end
    end

    def destroy
      @contribution = Contribution.find(params[:id])

      if request.headers[:apikey] == @contribution.user.apikey
        respond_to do |format|
          if @contribution.destroy
            format.json { head :ok }
          else
            format.json { render json: @contribution.errors, status: :unprocessable_entity }
          end
        end
      end
    end

    private

    def contribution_params
      params.permit(:title, :url, :text)
    end
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy, :vote]
  before_action :set_user_id_param, only: [:create, :update]

  def vote_up
    @contribution = Contribution.find(params[:id])
    @contribution.upvote_from current_user
    redirect_back fallback_location: :fallback_location
  end

  def unvote
    @contribution = Contribution.find(params[:id])
    @contribution.unvote_up current_user
    redirect_back fallback_location: :fallback_location
  end

  def ask
    @contributions = Contribution.questions
    @contributions.sort_by {@contributions |c| -c.get_upvotes.size }
  end

  def index
    if params[:id].present?
      @contributions = Contribution.where(user_id: params[:id])
      @contributions.sort_by { |c| -c.get_upvotes.size }
    else
      @contributions = Contribution.all
      @contributions.sort_by { |c| -c.get_upvotes.size }
    end
  end

  def show
  end

  def newest
    @contributions = Contribution.all.order created_at: :desc
  end

  def new
    flash[:alert] = nil
    if current_user.present? 
        @contribution = Contribution.new
    else 
    redirect_to '/auth/google_oauth2'
     end
  end

  def create

    @contribution = Contribution.new(contribution_params.merge!({user_id: params[:contribution][:user_id]}))
    respond_to do |format|
      if @contribution.save
        format.html { redirect_to root_path, notice: 'Contribution was successfully created.' }
        format.json { render :index, status: :created, location: @contribution }
          
      elsif  @contribution.errors[:url][0] == "is invalid"
        format.html { render :new }
        flash[:alert] = "Url is invalid"
      
      elsif @contribution.errors[:base][0] == "This contribution has url and text and can only have one."
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
        flash[:alert] = "This contribution has url and text and can only have one"
        
      elsif @contribution.errors[:title][0] == "can't be blank"
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
        flash[:alert] = "Title can't be blank"
        
      elsif  @contribution.url != ""
        if Contribution.find_by(url: params[:contribution][:url]) != nil
          format.html {redirect_to Contribution.find_by(url: params[:contribution][:url])}
        end
        
      else
          format.html { render :new }
          format.json { render json: @contribution.errors, status: :unprocessable_entity }
          flash[:alert] = "Introduce Url or Text"
        
      end
    end
  end
  
  

  def destroy
    if @contribution.user.id = current_user.id
      @contribution.destroy
      respond_to do |format|
        format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

    def set_contribution
      return if @contribution = Contribution.find(params[:id])

      redirect_to root_url
    end

    def set_user_id_param
      params[:contribution][:user_id] = current_user.id if current_user
    end

    def contribution_params
      params.require(:contribution).permit(:title, :url, :text)
    end
end

app/views/contributions/_contribution.html.erb
<li id="contribution-<%= contribution.id %>">

  <div class="title">
  <% if current_user.present? && contribution.user_id == current_user.id %>
    <span class="vote glyphicon glyphicon-asterisk"></span>
  <% elsif current_user.present? && contribution.user_id != current_user.id && current_user.voted_for?(contribution) %>
    <%= link_to vote_contribution_path(contribution), method: :delete do %>
      <span class="vote glyphicon glyphicon-circle-arrow-down"></span>
    <% end %>
  <% elsif %>
    <%= link_to vote_contribution_path(contribution), method: :post do %>
      <span  class="vote glyphicon glyphicon-circle-arrow-up"></span>
    <% end %>
  <% end %>
  
  <% if contribution.url.present? %>
    <%= link_to contribution.title, contribution.url, class: "url" %> <small class="from"> (<%=contribution.get_from%>)</small>
  <% else %>
    <%= link_to contribution.title, contribution, class: "url" %>
  <% end %>
  </div>

  <div class="content">
    <%= pluralize(contribution.get_upvotes.size, "points") %> by
    <span class="user"><%= link_to contribution.user.name, contribution.user %> </span>
    <span class="timestamp"><%= link_to time_ago_in_words(contribution.created_at)+" ago", contribution %></span> |
     <% if contribution.comments.size.zero? %>
      <span class="comments"><%= link_to "discuss", contribution %></span>
     <% else %>
      <span class="comments"><%= link_to pluralize(contribution.comments.size, " comments"), contribution %></span>
     <% end %>
  </div>

</li>

app/views/contributions/_form.html.erb
<div>
  <% if flash[:alert] %>
  <div class= "alert"> <%=flash[:alert] %></div>
  <% end %>
<%= form_for(@contribution) do |f| %>
      <div class="form-group">
        <%= f.label :title, class: "col-sm-2"  %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :url, class: "col-sm-2"  %>
        <%= f.text_field :url, class: "form-control"  %>
      </div>
      <div class="col-sm-12 center"><strong>or</strong></div>
      <div class="form-group">
        <%= f.label :text, class: "col-sm-2" %>
        <%= f.text_area :text, class: "form-control" %>
      </div>
      <div>
        <%= f.submit "submit", class: "btn btn-primary" %>
      </div>
    <% end %>
</div>

app/views/contributions/ask.html.erb
<% provide(:title, 'Asked') %>
<% if @contributions.any? %>
  <ol class="contributions">
    <%= render @contributions %>
  </ol>
<% end %>

app/views/contributions/index.html.erb
<% if @contributions.any? %>
  <ol class="contributions">
    <%= render @contributions %>
  </ol>
<% end %>

app/views/contributions/new.html.erb
<% provide(:title, "Submit") %>

<%= render 'form', contribution: @contribution %>

app/views/contributions/newest.html.erb
<% provide(:title, 'Newest') %>
<% if @contributions.any? %>
  <ol class="contributions">
    <%= render @contributions %>
  </ol>
<% end %>

app/views/contributions/show.html.erb
<% provide(:title, "#{@contribution.title}") %>
<h1><%= link_to @contribution.title, @contribution.url, class: "url" %> <% if @contribution.url.present? %><small class="from"> (<%= @contribution.get_from %>)</small><% end %></h1>

<div class="contribution_info">
  <table class="table">
    <tr>
      <td><strong style="float:right;">Points:</strong></td>
      <td><%= @contribution.get_upvotes.size %>
        <% if current_user.present? && @contribution.user_id == current_user.id %>
          <span class="vote glyphicon glyphicon-asterisk"></span>
        <% elsif current_user.present? && @contribution.user_id != current_user.id && current_user.voted_for?(@contribution) %>
          <%= link_to vote_contribution_path(@contribution), method: :delete do %>
            <span class="vote glyphicon glyphicon-circle-arrow-down"></span>
          <% end %>
        <% elsif %>
          <%= link_to vote_contribution_path(@contribution), method: :post do %>
            <span class="vote glyphicon glyphicon-circle-arrow-up"></span>
          <% end %>
        <% end %>
      </td>
      <td><strong style="float:right;">By:</strong></td>
      <td><%= @contribution.user.name %></td>
      <td><strong style="float:right;">Created:</strong></td>
      <td><%= time_ago_in_words(@contribution.created_at)+" ago" %></td>
    </tr>
  </table>
  <% if @contribution.ask %>
    <table class="table">
      <tr>
        <td class="col-xs-1"><strong style="float:right;">Text:</strong></td>
        <td class="col-xs-11"><%= @contribution.text %></td>
      </tr>
    </table>
  <% end %>
  
</div>

<div>
  <%= form_for (@contribution.comments.new) do |f| %>
    <%= hidden_field_tag :type , 'contribution' %>
    <div class="form-group">
      <%= f.text_area :text, class: "form-control" %>
    </div>
    <div>
      <%= f.submit "submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>
<br/>

<% if @contribution.comments.any? %>
<div class="comments">
  <%= render @contribution.comments %>
</div>
<% end %>

app/views/contributions/voted_contributions.html.erb
<% if @contributions.any? %>
  <ol class="contributions">
    <%= render @contributions %>
  </ol>
<% end %>