config/routes.rb
Rails.application.routes.draw do
  root 'contributions#index'

  resources :contributions do
    member do
      post '/vote', to: "contributions#vote_up"
      delete '/vote', to: "contributions#unvote"

      resources :comments
    end
  end

  resources :comments do
    member do
      post '/vote', to: "comments#vote_up"
      delete '/vote', to: "comments#unvote"

      resources :comments
    end
  end

  resources :users do
    member do
      get '/contributions', to: "users#contributions"
      get '/voted_contributions', to: "users#voted_contributions"
      get '/comments', to: "users#comments"
      get '/voted_comments', to: "users#voted_comments"
    end
  end

  get '/submit', to: "contributions#new"
  get '/newest', to: "contributions#newest"
  get '/ask', to: "contributions#ask"

  # Authentication
  post '/login', to:'sessions#authenticate'

  namespace :api do
    resources :users, only: %i(index update show) do
      member do
        get '/contributions', to: "users#contributions"
        get '/voted_contributions', to: "users#voted_contributions"
        get '/comments', to: "users#comments"
        get '/voted_comments', to: "users#voted_comments"
      end
    end

    resources :contributions do
      member do
        post '/vote', to: "contributions#vote_up"
        delete '/vote', to: "contributions#unvote"
        post '/comments', to: "comments#createFromContribution"
      end
    end

    resources :comments, only: %i(show update) do
      member do
        post '/vote', to: "comments#vote_up"
        delete '/vote', to: "comments#unvote"
        post '/replies', to: "comments#createFromComment"
      end
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Hacker News", root_path, id: "logo" %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li <% if yield(:title).present? && yield(:title)=="Newest" %>
            class="active"
          <% end %>>
          <%= link_to "New", newest_path %>
        </li>
        <% if current_user.present?%>
          <li<% if yield(:title).present? && yield(:title) == "#{current_user.name}'s comments" %>
            class="active"
          <% end %>>
          <a href="/users/<%= current_user.id%>/comments">Thread</a>
          
        <% end %>
        <li<% if yield(:title).present? && yield(:title)=="Asked" %>
            class="active"
          <% end %>>
          <%= link_to "Ask", ask_path %></li>
        <li<% if yield(:title).present? && yield(:title)=="Submit" %>
            class="active"
          <% end %>>
          <%= link_to "Submit", submit_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li<% if yield(:title).present? && yield(:title)==current_user.name %>
            class="active"
            <% end %>>
            <%= link_to current_user.name, current_user%>
          </li>
          <li><%= link_to "SignOut", signout_path, id: "sign_out", class: "glyphicon glyphicon-log-out" %></li>
        <% else %>
          <li><%= link_to "LogIn", "/auth/google_oauth2", id: "sign_in", class: "glyphicon glyphicon-log-in" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>